from app.repositories.vessel_repository import VesselRepository
from app.repositories.ais_record_repository import AISRecordRepository
from app.repositories.anomaly_repository import AnomalyRepository
from app.repositories.satellite_repository import SatelliteRepository
from app.repositories.spill_repository import SpillRepository
from app.repositories.risk_zone_repository import RiskZoneRepository
from app.repositories.alert_repository import AlertRepository
from app.repositories.response_action_repository import ResponseActionRepository